defmodule Tunez.Repo.Migrations.AddArtistReferenceToAlbum do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:albums) do
      modify :artist_id, :uuid
    end

    create index(:albums, [:artist_id])
  end

  def down do
    drop_if_exists index(:albums, [:artist_id])

    alter table(:albums) do
      modify :artist_id, :uuid
    end
  end
end
